[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 20
normal = { family = "IBM Plex Mono", style = "Regular" }
bold = { family = "IBM Plex Mono", style = "Bold" }
italic = { family = "IBM Plex Mono", style = "Italic" }
bold_italic = { family = "IBM Plex Mono", style = "Bold Italic" }

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty@CachyOS"
opacity = 1
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors.primary]
background = "#ffffff"
# background = "#eff1f5"
foreground = "#4c4f69"
dim_foreground = "#8c8fa1"
bright_foreground = "#4c4f69"

[colors.cursor]
text = "#eff1f5"
cursor = "#dc8a78"

[colors.vi_mode_cursor]
text = "#eff1f5"
cursor = "#7287fd"

[colors.search.matches]
foreground = "#eff1f5"
background = "#6c6f85"

[colors.search.focused_match]
foreground = "#eff1f5"
background = "#40a02b"

[colors.footer_bar]
foreground = "#eff1f5"
background = "#6c6f85"

[colors.hints.start]
foreground = "#eff1f5"
background = "#df8e1d"

[colors.hints.end]
foreground = "#eff1f5"
background = "#6c6f85"

[colors.selection]
text = "#eff1f5"
background = "#dc8a78"

[colors.normal]
black = "#bcc0cc"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#5c5f77"

[colors.bright]
black = "#acb0be"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#6c6f85"

[[colors.indexed_colors]]
index = 16
color = "#fe640b"

[[colors.indexed_colors]]
index = 17
color = "#dc8a78"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Underline"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
