fork = true
frame = "none"
idle = false

maximized = false

[font]
normal = [
  "Lilex",
  "JetBrains Mono",
  "Symbols Nerd Font",
  "Noto Color Emoji",
] # Will use the bundled Fira Code Nerd Font by default
size = 17.0
